name: instagram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
  fonts:
    - family: "Satisfy"
      fonts:
        - asset: assets/fonts/satisfy.ttf
